improved README with better markdown and more examples provided instructions if mount-encrypted-folder and unmount-encrypted-folder are run without prameters

diff --git a/server/unmount-encrypted-folder b/server/unmount-encrypted-folder
--- a/server/unmount-encrypted-folder
+++ b/server/unmount-encrypted-folder
@@ -1,4 +1,10 @@
 #!/bin/bash
+if [ "$1" == "" ];
+then
+  echo "You must provide the name of the folder the encrypted directory is mounted in as a parameter."
+  echo "Example: $0 my-backup  # this will unmount my-backup from .my-backup-encrypted, if it is mounted"
+  exit 100
+fi
 BACKUP_DIR="`readlink -f $1`"
 echo "Unmounting \"$BACKUP_DIR\"..."
 if [ -d "$BACKUP_DIR" ];
@@ -20,6 +26,6 @@ then
     exit 0
   fi
 else
-  echo -n "ERROR: Directory \"$BACKUP_DIR\" does not exist"
+  echo "ERROR: Directory \"$BACKUP_DIR\" does not exist"
   exit 101
 fi
